### PR TITLE
Handle JFIF headers.

### PR DESCRIPTION
**Pull request by hinxx**
This change skips over JFIF EXIF headers and finds JPEG EXIF header, if it exists.
Minor change to detection of JPEG endinaness in order to make library more roboust.

### CODE REVIEW

**Comment by jernejaMislej** [comment]
load does not fail anymore even if jfif header present, but tests dont go through, seems like some tags are lost
needs more debugging

**Comment by hinxx** [comment]
Looks like we had two Exif segments with the previous pull request. I'm not sure how bad this is..

This was due to the way piexif was handling the location of Exif segment (always after SOI, in APP1 or APP0), when calling insert(). This was conflicting with JFIF segment that wanted to be in the same place. 

New pull request will try to find the existing Exif segment and replace that one instead of forcing the Exif segment to be right after SOI. This will keep other segments (JFIF) intact and still allow Exif to be manipulated.

**Comment by hinxx** [comment]
Simple python script to test the behavior: [my_test1.txt](https://github.com/mapillary/Piexif/files/1736857/my_test1.txt)
It will call ExifEdit.add_direction(1) and output a new file.

Here is exiftool -v3 dump of input file:
[input.txt](https://github.com/mapillary/Piexif/files/1736864/input.txt)

Here is exiftool -v3 dump of output file:
[output.txt](https://github.com/mapillary/Piexif/files/1736865/output.txt)


Notice the addition of newly added lines in the output.txt:

```
  | | 8)  GPSImgDirectionRef = T
  | |     - Tag 0x0010 (2 bytes, string[2]):
  | |         0c3d: 54 00                                           [T.]
  | | 9)  GPSImgDirection = 1 (100/100)
  | |     - Tag 0x0011 (8 bytes, rational64u[1]):
  | |         0cb5: 00 00 00 64 00 00 00 64                         [...d...d]
```

**Comment by hinxx** [comment]
@jernejaMislej there is no more pdb invocation in the _common.py with this PR.

**Comment by jernejaMislej** [comment]
thank you so much for contributing! merging now

**Pull request merged**
